### ISSUE TITLE
PHP Scope and Github link in MD file

### ISSUE THREAD

**Issue by utilis** [ndeet/unzipper#1]
Hi, 

Upon testing, please may I suggest adding a PHP working environment scope and your Git Hub Link in to the MD file. 

I get a white screen on PHP 5.2, but works perfectly on 5.3 and 5.4 via standard hosting Eco systems. 

If you require more info, i would be happy to help.

Ps. Thank you for the code, it has saved me hours.

**Comment by ndeet** [comment]
Hi,

you are right, requirements and updates info added. Thanks!

Regarding the PHP 5.2 white screen - the white screen means only that the error output is disabled by the host. You may find the error message in a log file. (e.g. search google "php white screen") 
I could debug this and make it working with PHP 5.2 - BUT - as it has been not supportet for some years now and does not receive security updates I do not want to support unsecure PHP versions. There are too many hosts running outdated and vulnerable PHP versions out there ;)

**Comment by utilis** [comment]
Very good point, not worth supporting 5.2 as it is unsecure, I did not think of that at the time of posting Doh, We use 5.4 as a minimum in order to help encourage hosts to keep up to date. Thank you for the quick response.
