### ISSUE TITLE
Tar unpack

### ISSUE THREAD

**Issue by hausmaen** [ndeet/unzipper#11]
worked fine but tar.gz is only creating a tar file instead of deflating the whole structure. TAR files are not recognized in combo box neither so I cant finish job with this tool. would be great if could be extended.

thank you

**Comment by ndeet** [comment]
Good point. Current use case was to extract dump.sql.gz which ends up in dump.sql  but to extract tar.gz archives too makes also sense, yes. To finish your job you can create .zip archive which is already supported ;)

**Comment by ndeet** [comment]
This has been resolved with the latest release 0.1.1 
https://github.com/ndeet/unzipper/releases/tag/0.1.1
