### ISSUE TITLE
php script breaks and displays in browser

### ISSUE THREAD

**Issue by iwanwilaga** [ndeet/unzipper#17]
Hello Andreas,

I try to run the unzip.php (ftp://{mywebhost}.hu/public_html/unzipper.php) in Firefox and it breaks and displays the scripts as html, the whole portion from exactly this line: "prepareExtraction($archive, $destination); ..."   until the very end of the file. Seems that the "->"  causes it (in " ->prepareExtraction" ).
And at the end the unzip + zip boxes displayed. (the unbroken html part of the sourcecode). 

![2019-01-22_220745](https://user-images.githubusercontent.com/35199604/51565702-f3737780-1e92-11e9-9716-193047668f3d.png)
![2019-01-22_220801](https://user-images.githubusercontent.com/35199604/51565703-f3737780-1e92-11e9-9866-3d6a0a7d67e2.png)

Is it common or just happens at my settings? Why is this happening? 
Thanks a lot, man! Best wishes,
Wiktor

**Comment by ndeet** [comment]
Hi Iwan,

interesting bug. When I look at your zip dropdown the name `$zip` is suspicious, it could very well be that this breaks it. Can you try to **not** use any special characters in your zip-archive name and see if it fixes the problem? e.g. rename to `some-zip-archive.zip`?

Also please let me know your current .zip archive names so that I can try to reproduce.

**Comment by iwanwilaga** [comment]
Andreas,

OK..., i found it..  i was trying to run the php in browser with an ftp:// protocol  instead http(s) in the url. Because in rush i just copied the url out from an ftp client. In this case that's quite negative to do so :)). That's why it treated the '->' as a special tag or operator (or smt like that) i guess ;).  Sorry, it was a bit late night when it happened. SO all is clear, by http(s) all works properly. 

Happy Developing to ya, man! Thank you,
W

**Comment by ndeet** [comment]
Hi Iwan,
thanks for reporting back and good that it is no bug.
