### ISSUE TITLE
This is not an issue but a request

### ISSUE THREAD

**Issue by yadavji83** [ndeet/unzipper#2]
This is a great and very handy tool. It would be awesome if you could create a similar tool to compress folders in zip.

**Comment by x-c0d3rz** [comment]
Would be too cool ♥,I'll do this as pull request when I've free-time

**Comment by ndeet** [comment]
Hi @yadavji83!
As of version 0.1.0 this is now built in.
https://github.com/ndeet/unzipper/releases/tag/0.1.0

**Comment by pyramiddesign** [comment]
UNSUBSCRIBE
On 23 Jul 2016, at 14:04, Andreas Tasch wrote:

> Hi @yadavji83!
> As of version 0.1.0 this is now built in.
> https://github.com/ndeet/unzipper/releases/tag/0.1.0
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Kind Regards,
David Martin

Multichannel | Creative | Marketing
Pyramid
Oddfellows Hall
6 Clarence Terrace
Warwick Street
Leamington Spa
CV32 5LD

t. 01926 316652
f. 01926 457290
w. www.pyramid-design.co.uk

Our Mission
To bring our clients closer to their customers through our unique combination of strategic thinking and creativity, driven by passion, delivered with pride
