### ISSUE TITLE
Said completed job, yet nothing happened.

### ISSUE THREAD

**Issue by JohnDarrell** [ndeet/unzipper#8]
Tried it on 000webhost account. Script gui loaded fine, ran it on 48MB archive, job done 1.4 seconds, no files. What did I do wrong?

**Comment by ndeet** [comment]
Hi,

not sure what went wrong, needs some further testing.

Test a) Check if hosting is bad by trying to extract the same archive on another host.

Test b) Check if archive is bad and try with another archive.

**Comment by ndeet** [comment]
Closing as no repsonse.
